---
- name: Users and Groups
  hosts: all
  become: yes

  var_files:
    - vars/user_list.yml
    - secret.yml

  tasks:
    - name: user create in webserver groups
      user
        name: {{ users.username }}
        password: {{ user_password | hash(sha512) }}
        group: wheel
        shell: /bin/bash
      when: inventory_hostname in groups['webservers']
      loop: users.uid > 1000 & users.uid < 2000

    - name: ssh kery file copy
      authorized_key
        user: {{ users.username }}
        state: present
        key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"

    - name: user create in database groups
      user
        name: {{ users.username }}
        password: {{ user_password | hash(sha512) }}
        group: wheel
        shell: /bin/bash
      when: inventory_hostname in groups['database']
      loop: users.uid > 2000
